package message;

public enum MsgError {
    WRONGPASSWORD,
    USERCREATED,
    NOTFOLLOWING,
    NOSUCHUSER,
    NOSUCHPHOTO,
    ALREADYFOLLOWING,
    ALREADYNOTFOLLING,
    DUPLICATEPHOTO,
    ALREADYLIKED,
    ALREADYDISLIKED,
}
