package message;

public enum MsgType {
    STARTSESSION,
    ENDSESSION,
    ADDPHOTO,
    ALLPHOTOSDATA,
    PHOTOOPINION,
    ALLPHOTOS,
    COMMENTPHOTO,
    LIKEPHOTO,
    DISLIKEPHOTO,
    FOLLOWUSER,
    UNFOLLOWUSER
}
