package message;

public enum MsgError {
    WRONGPASSWORD,
    USERCREATED,
    NOTFOLLOWING,
    NOSUCHUSER,
    NOSUCHPHOTO,
    ALREADYFOLLOWING,
    ALREADYNOTFOLLOWING,
    DUPLICATEPHOTO,
    ALREADYLIKED,
    ALREADYDISLIKED
}
